
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/dorm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=dorm_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Изменение порта на 8080

  mongo:
    image: mongo
    volumes:
      - dorm-mongo-data:/data/db
    ports:
      - "27017:27017"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: dorm_db
    volumes:
      - dorm-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dorm-mongo-data:
  dorm-postgres-data: